const data = {
  products: [
    {
      id: 1,
      slug: "headphone",
      name: "headphone",
      category: "music",
      price: "200 tk",
      image:
        "https://gadgetsbysadi.com/wp-content/uploads/2023/03/download.jpg",
      brand: "KZ",
      rating: 4.5,
      numReviews: 10,
      contentInStock: 30,
      description: "This is a sample description",
    },
    {
      id: 2,
      slug: "speaker",
      name: "speaker",
      category: "music",
      price: "350 tk",
      image:
        "https://gadgetsbysadi.com/wp-content/uploads/2023/03/4EE37916-8748-4031-ADE6-42F8AF4E5409-300x300.jpeg",
      brand: "Havit",
      rating: 5.0,
      numReviews: 3,
      contentInStock: 30,
      description: "This is a sample description",
    },
    {
      id: 3,
      slug: "earphone",
      name: "earphone",
      category: "music",
      price: "100 tk",
      image:
        "https://gadgetsbysadi.com/wp-content/uploads/2023/03/Lenovo-HF140-Wired-Headphones-600x600.jpg",
      brand: "A4Tech",
      rating: 4.0,
      numReviews: 1,
      contentInStock: 30,
      description: "This is a sample description",
    },
    {
      id: 4,
      slug: "pinkearphone",
      name: "pinkearphone",
      category: "headphone",
      price: "200 tk",
      image: "https://gadgetsbysadi.com/wp-content/uploads/2023/03/OIP-1.jpg",
      brand: "KZP",
      rating: 4.5,
      numReviews: 10,
      contentInStock: 30,
      description: "This is a sample description",
    },
    {
      id: 5,
      slug: "white-earphone",
      name: "white-earphone  ",
      category: "headphoneStudio",
      price: "200 tk",
      image:
        "https://gadgetsbysadi.com/wp-content/uploads/2023/03/xinji-stone-m1-tws-earbuds-2.jpg",
      brand: "KZS",
      rating: 4.5,
      numReviews: 10,
      contentInStock: 30,
      description: "This is a sample description",
    },
    {
      id: 6,
      slug: "bluetoothearphone",
      name: "bluetoothearphone",
      category: "headphone",
      price: "200 tk",
      image:
        "https://gadgetsbysadi.com/wp-content/uploads/2023/03/Original-Air-Pro-60-TWS-Fone-Bluetooth-Earphones-Touch-Control-Earbuds-with-Mic-Wireless-Bluetooth-Headset.jpg_640x640-600x600.jpg",
      brand: "KZN",
      rating: 4.5,
      numReviews: 10,
      contentInStock: 30,
      description: "This is a sample description",
    },

    {
      id: 7,
      slug: "usbcable",
      name: "usbcable",
      category: "cables",
      price: "10 tk",
      image:
        "https://gadgetsbysadi.com/wp-content/uploads/2023/03/508a993e80682f666194739d4b9a53b4.png_720x720q80-1-300x300.png",
      brand: "A4",
      rating: 4.0,
      numReviews: 1,
      contentInStock: 30,
      description: "This is a sample description",
    },
  ],
};

export default data;
